eureka:
  client:
    serviceUrl:
      #admin用户，123456密码
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    #自定义元数据
    metadata-map:
      my-metadata: aaaaaaaaaa

server:
  port: 8763

spring:
  application:
    name: service-hi
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

logging:
  level: info
  org.hibernate: info
  org.hibernate.type.descriptor.sql.BasicBinder: trace
  org.hibernate.type.descriptor.sql.BasicExtractor: trace

